<?php namespace Modules\Quotes\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class QuotesQuoteTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		// Model::unguard();
		// \DB::table('quote_quotes')->truncate();
        \DB::table('quote_quotes')->insert([
            [
                'opportunity_id_fk' => '1',
                'quote_number' => '100000',
                'quote_option' => 'A',
                'revision_number' => '1',
                'title' => 'Test Quote Option A Rev 1',
                'remarks' => null,

                'quote_status_id_fk' => '1',
                'total_material_cost' => '10000.00',
                'total_fabric_install_cost' => '2000.00',
                'total_glass_cost' => '200.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '25000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '25000.00',
                'vat' => '3250',
                'grand_total' => '28250',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
                'opportunity_id_fk' => '1',
                'quote_number' => '100000',
                'quote_option' => 'A',
                'revision_number' => '2',
                'title' => 'Test Quote Option A Rev 2',
                'remarks' => null,

                'quote_status_id_fk' => '1',
                'total_material_cost' => '10500.00',
                'total_fabric_install_cost' => '2500.00',
                'total_glass_cost' => '220.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '30000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '30000.00',
                'vat' => '3250',
                'grand_total' => '33250',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
                'opportunity_id_fk' => '1',
                'quote_number' => '100000',
                'quote_option' => 'B',
                'revision_number' => '1',
                'title' => 'Test Quote Option B Rev 1',
                'remarks' => null,

                'quote_status_id_fk' => '1',
                'total_material_cost' => '5000.00',
                'total_fabric_install_cost' => '500.00',
                'total_glass_cost' => '50.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '10000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '10000.00',
                'vat' => '250',
                'grand_total' => '5250',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
                'opportunity_id_fk' => '1',
                'quote_number' => '100000',
                'quote_option' => 'C',
                'revision_number' => '1',
                'title' => 'Test Quote Option C Rev 1',
                'remarks' => null,
                'quote_status_id_fk' => '1',

                'total_material_cost' => '7500.00',
                'total_fabric_install_cost' => '500.00',
                'total_glass_cost' => '50.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '10000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '7500.00',
                'vat' => '500',
                'grand_total' => '10000',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
                'opportunity_id_fk' => '1',
                'quote_number' => '100000',
                'quote_option' => 'C',
                'revision_number' => '2',
                'title' => 'Test Quote Option C Rev 2',
                'remarks' => null,
                'quote_status_id_fk' => '1',

                'total_material_cost' => '10000.00',
                'total_fabric_install_cost' => '500.00',
                'total_glass_cost' => '50.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '10000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '7500.00',
                'vat' => '500',
                'grand_total' => '17500',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
            		'opportunity_id_fk' => '2',
                'quote_number' => '100001',
                'quote_option' => 'A',
                'revision_number' => '1',
                'title' => 'Test Quote 2 Option A Rev 1',
                'remarks' => null,
                
                'quote_status_id_fk' => '1',
                'total_material_cost' => '10000.00',
                'total_fabric_install_cost' => '2000.00',
                'total_glass_cost' => '200.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '25000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '25000.00',
                'vat' => '3250',
                'grand_total' => '28250',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
                'opportunity_id_fk' => '2',
                'quote_number' => '100001',
                'quote_option' => 'A',
                'revision_number' => '2',
                'title' => 'Test Quote 2 Option A Rev 2',
                'remarks' => null,

                'quote_status_id_fk' => '1',
                'total_material_cost' => '10500.00',
                'total_fabric_install_cost' => '2500.00',
                'total_glass_cost' => '220.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '30000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '30000.00',
                'vat' => '3250',
                'grand_total' => '33250',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
                'opportunity_id_fk' => '2',
                'quote_number' => '100001',
                'quote_option' => 'B',
                'revision_number' => '1',
                'title' => 'Test Quote 2 Option B Rev 1',
                'remarks' => null,

                'quote_status_id_fk' => '1',
                'total_material_cost' => '5000.00',
                'total_fabric_install_cost' => '500.00',
                'total_glass_cost' => '50.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '10000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '10000.00',
                'vat' => '250',
                'grand_total' => '5250',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
                'opportunity_id_fk' => '2',
                'quote_number' => '100001',
                'quote_option' => 'B',
                'revision_number' => '2',
                'title' => 'Test Quote 2 Option B Rev 2',
                'remarks' => null,
                'quote_status_id_fk' => '1',

                'total_material_cost' => '7500.00',
                'total_fabric_install_cost' => '500.00',
                'total_glass_cost' => '50.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '10000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '7500.00',
                'vat' => '500',
                'grand_total' => '10000',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ],
            [
                'opportunity_id_fk' => '2',
                'quote_number' => '100001',
                'quote_option' => 'B',
                'revision_number' => '3',
                'title' => 'Test Quote 2 Option B Rev 3',
                'remarks' => null,
                'quote_status_id_fk' => '1',

                'total_material_cost' => '10000.00',
                'total_fabric_install_cost' => '500.00',
                'total_glass_cost' => '50.00',
                'pc_unforseen' => '5.00',
                'pc_engg_mgmt' => '5.00',
                'pc_markup' => '10.00',
                'pc_glass_markup' => '5.00',
                'pc_glass_wastage' => '4.00',
                'is_include_vat' => '0',
                'sub_total' => '10000.00',
                'discount' => '0.00',
                'pc_discount' => '0.00',
                'sub_total_discounted' => '7500.00',
                'vat' => '500',
                'grand_total' => '17500',

                'product_category_id_fk' => '1',
                'is_glass' => '0',
                'glass_type_id_fk' => null,

                'created_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                'updated_at' => \Carbon\Carbon::createFromDate(2016, 3, 17)->toDateTimeString(),
                 'created_by'=>'Ram',
                 'updated_by'=>'Ram',
                 'deleted_by'=> 'NULL',  
                 'deleted_at'=>'NULL',
            ]            
        ]);
		// $this->call("OthersTableSeeder");
	}

}